name: Auto Release By Tag Using GoReleaser
on:
  push:
    branches: 
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo this tag will be release by go releaser!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Hello, I am going to work now
        echo if there is anything wrong, call if off
    - name: goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
